version: '3.11'
services:
  redis:
    image: redis
    container_name: redis-broker
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis/data:/data
    restart: always

  db:
    image: postgres
    container_name: DB_EbookTranslate
    environment:
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: DB_admin_page
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80

volumes:
  postgres_data: